#!/bin/bash
#
# phase1.sh - Phase 1: Base OS hardening and prep
#
# Idempotent. Safe to re-run. Each step checks current state before acting.
# Produces a summary report at the end.
#
# Run as root: bash phase1.sh
#
# Passwords for the admin users are NOT printed by this script. They are
# in CREDENTIALS.txt (generated by phase0-bootstrap.sh) at the repo root.
#

set -u  # error on undefined variable; we don't use -e because we want to handle errors per-step

# ============================================================================
# CONFIGURATION
# ============================================================================
ADMIN_USER="wayne"
SHARED_ADMIN_USER="admin"
STAFF_USER="$SHARED_ADMIN_USER"  # backward-compat alias
SSH_PORT="2222"
HOSTNAME_FQDN="docenttemplate.com"
HOSTNAME_SHORT="docenttemplate"
TIMEZONE="America/Los_Angeles"
SERVER_IP=""  # populated from tenant.local; falls back to detection if unset

# === BEGIN tenant.local/secrets.local source block (added by phase0 design) ===
# Source per-tenant config and secrets if they exist. These files are created
# by phase0-bootstrap.sh. If they are not present, the hardcoded defaults
# above remain in effect (preserving original standalone behavior).
__PHASE_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__PHASE_REPO_ROOT="$(dirname "$__PHASE_SCRIPT_DIR")"
if [ -f "$__PHASE_REPO_ROOT/tenant.local" ]; then
    # shellcheck disable=SC1091
    source "$__PHASE_REPO_ROOT/tenant.local"
fi
if [ -f "$__PHASE_REPO_ROOT/secrets.local" ]; then
    # shellcheck disable=SC1091
    source "$__PHASE_REPO_ROOT/secrets.local"
fi
unset __PHASE_SCRIPT_DIR __PHASE_REPO_ROOT
# === END tenant.local/secrets.local source block ===

# Backward-compat: in older phase0 versions, only STAFF_USER was set.
# In newer versions, SHARED_ADMIN_USER is the canonical name.
if [ -z "${SHARED_ADMIN_USER:-}" ] && [ -n "${STAFF_USER:-}" ]; then
    SHARED_ADMIN_USER="$STAFF_USER"
fi
if [ -z "${STAFF_USER:-}" ] && [ -n "${SHARED_ADMIN_USER:-}" ]; then
    STAFF_USER="$SHARED_ADMIN_USER"
fi

# If SERVER_IP wasn't provided by tenant.local, detect it
if [ -z "${SERVER_IP:-}" ]; then
    SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
    [ -z "$SERVER_IP" ] && SERVER_IP="(unknown)"
fi

# ============================================================================
# REPORT TRACKING
# ============================================================================
REPORT=()

log_done()    { REPORT+=("[DONE]    $1"); echo "  ✓ $1"; }
log_skip()    { REPORT+=("[SKIPPED] $1 (already done)"); echo "  - $1 (already done)"; }
log_warn()    { REPORT+=("[WARN]    $1"); echo "  ! $1"; }
log_fail()    { REPORT+=("[FAIL]    $1"); echo "  ✗ $1"; }

step() { echo ""; echo "=== $1 ==="; }

# ============================================================================
# SAFETY CHECK
# ============================================================================
if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: This script must be run as root."
    exit 1
fi

echo "==================================================================="
echo "  Phase 1 - Base OS hardening for $HOSTNAME_FQDN"
echo "  $(date)"
echo "==================================================================="

# ============================================================================
# STEP 1: OS sanity check, updates, and reboot detection
# ============================================================================
step "Step 1: OS sanity check and package updates"

# --- Check 1: Verify Ubuntu 26.04 LTS ---
if [ ! -f /etc/os-release ]; then
    echo ""
    echo "  ERROR: /etc/os-release not found. Cannot verify OS."
    echo "  This build is designed for Ubuntu 26.04 LTS only."
    echo "  Aborting."
    exit 1
fi

. /etc/os-release

if [ "$NAME" != "Ubuntu" ] || [ "$VERSION_ID" != "26.04" ]; then
    echo ""
    echo "  ERROR: This build is designed for Ubuntu 26.04 LTS."
    echo "         Detected: $NAME $VERSION_ID"
    echo ""
    echo "  Phase scripts have been written and tested specifically"
    echo "  for Ubuntu 26.04 LTS (Resolute Raccoon). Running on a"
    echo "  different version may break things in unpredictable ways"
    echo "  (different package versions, config formats, etc.)."
    echo ""
    echo "  Specifically, phase 4 expects Dovecot 2.4 syntax which"
    echo "  ships with 26.04. Older versions ship Dovecot 2.3."
    echo ""
    echo "  Aborting. Provision a fresh Ubuntu 26.04 LTS server and retry."
    exit 1
fi
log_done "OS verified: Ubuntu 26.04 LTS"

# --- Check 2: Show pending updates and prompt before applying ---
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
UPGRADABLE_OUTPUT=$(apt list --upgradable 2>/dev/null | grep -v "^Listing" || true)
UPGRADABLE_COUNT=$(echo "$UPGRADABLE_OUTPUT" | grep -cv "^$" || true)

if [ "$UPGRADABLE_COUNT" -eq 0 ]; then
    log_skip "OS packages already up to date"
else
    SECURITY_COUNT=$(echo "$UPGRADABLE_OUTPUT" | grep -c "security" || true)
    echo ""
    echo "  Pending updates: $UPGRADABLE_COUNT packages ($SECURITY_COUNT security updates)"
    echo ""
    echo "  Phase 1 will now apply these updates. This may take 1-3 minutes."
    echo ""
    read -r -p "  Continue and apply updates? (type 'yes' to proceed): " confirm
    case "$confirm" in
        yes|YES)
            apt-get upgrade -y -qq -o Dpkg::Use-Pty=0 < /dev/null
            log_done "Applied $UPGRADABLE_COUNT package updates"
            ;;
        *)
            echo "  Aborted (you must type 'yes' to proceed). No changes made."
            exit 1
            ;;
    esac
fi

# --- Check 3: Detect if reboot is required after updates ---
if [ -f /var/run/reboot-required ]; then
    echo ""
    echo "==================================================================="
    echo "  REBOOT REQUIRED"
    echo "==================================================================="
    echo ""
    echo "  System updates installed a new kernel or critical libraries that"
    echo "  require a reboot before they take effect."
    echo ""
    echo "  Phase 1 cannot continue safely until the server has rebooted."
    echo ""
    echo "  WHAT WILL HAPPEN:"
    echo "    1. This script will trigger a reboot in a moment."
    echo "    2. Your SSH session will disconnect (this is normal)."
    echo "    3. Wait ~30-60 seconds for the server to come back up."
    echo "    4. SSH back in as root on port 22 (same as you did before)."
    echo "    5. Re-run phase 1 with the SAME command you used to start it:"
    echo ""
    echo "         sudo bash /root/server-build/scripts/phase1.sh"
    echo ""
    echo "    6. Phase 1 is idempotent: already-completed steps will be"
    echo "       skipped, and it will continue from this point."
    echo ""
    echo "==================================================================="
    echo ""
    read -r -p "Type 'yes' to reboot now (anything else aborts): " reboot_confirm
    if [ "$reboot_confirm" = "yes" ]; then
        echo ""
        echo "  Rebooting in 5 seconds. SSH back in and re-run phase 1."
        echo ""
        sleep 5
        # systemd-managed reboot - the safest way to trigger it programmatically
        systemctl reboot
        # If we get here, the reboot didn't take effect. Exit so user can debug.
        echo "  systemctl reboot did not take effect. Try manually: reboot"
        exit 1
    else
        echo ""
        echo "  Reboot aborted. Phase 1 stopped."
        echo "  When you're ready, run:  reboot"
        echo "  Then SSH back in and re-run phase 1."
        echo ""
        exit 1
    fi
fi
log_done "No reboot required"

# --- Check 4: Kernel sanity check ---
# Even when /var/run/reboot-required isn't present, there can be a mismatch
# between the running kernel (uname -r) and the highest installed kernel
# package. This happens occasionally when Ubuntu's update tooling skips
# creating the reboot-required marker. Catch it here.
RUNNING_KERNEL="$(uname -r)"
# Get the highest installed linux-image-* package version (sorted by version,
# not lexically). dpkg-query gives us "package\tversion" lines.
INSTALLED_KERNEL_PKG="$(
    dpkg-query -W -f='${Package}\n' 'linux-image-[0-9]*' 2>/dev/null \
    | sed 's/^linux-image-//' \
    | sort -V \
    | tail -1
)"

if [ -n "$INSTALLED_KERNEL_PKG" ] && [ "$RUNNING_KERNEL" != "$INSTALLED_KERNEL_PKG" ]; then
    echo ""
    echo "==================================================================="
    echo "  KERNEL MISMATCH - REBOOT RECOMMENDED"
    echo "==================================================================="
    echo ""
    echo "  Running kernel:    $RUNNING_KERNEL"
    echo "  Installed kernel:  $INSTALLED_KERNEL_PKG"
    echo ""
    echo "  These differ. The system is running a kernel that has been"
    echo "  superseded by a newer one on disk. A reboot will swap kernels."
    echo ""
    echo "  Ubuntu didn't flag this with /var/run/reboot-required, but it"
    echo "  is the same situation: the right thing to do is reboot before"
    echo "  continuing. Otherwise the rest of phase 1 may configure things"
    echo "  against the older kernel."
    echo ""
    echo "  WHAT WILL HAPPEN:"
    echo "    1. This script will trigger a reboot in a moment."
    echo "    2. Your SSH session will disconnect (this is normal)."
    echo "    3. Wait ~30-60 seconds for the server to come back up."
    echo "    4. SSH back in as root on port 22 (same as you did before)."
    echo "    5. Re-run phase 1 with the SAME command:"
    echo ""
    echo "         sudo bash /root/server-build/scripts/phase1.sh"
    echo ""
    echo "==================================================================="
    echo ""
    read -r -p "Type 'yes' to reboot now (anything else aborts): " reboot_confirm
    if [ "$reboot_confirm" = "yes" ]; then
        echo ""
        echo "  Rebooting in 5 seconds. SSH back in and re-run phase 1."
        echo ""
        sleep 5
        systemctl reboot
        echo "  systemctl reboot did not take effect. Try manually: reboot"
        exit 1
    else
        echo ""
        echo "  Reboot aborted. Phase 1 stopped."
        echo "  When you're ready, run:  reboot"
        echo "  Then SSH back in and re-run phase 1."
        echo ""
        exit 1
    fi
fi
log_done "Kernel sanity check passed (running: $RUNNING_KERNEL)"

# ============================================================================
# STEP 2: Set hostname
# ============================================================================
step "Step 2: Setting hostname to $HOSTNAME_SHORT"

CURRENT_HOSTNAME=$(hostname)
if [ "$CURRENT_HOSTNAME" = "$HOSTNAME_SHORT" ]; then
    log_skip "Hostname already set to $HOSTNAME_SHORT"
else
    hostnamectl set-hostname "$HOSTNAME_SHORT"
    log_done "Hostname set to $HOSTNAME_SHORT (was: $CURRENT_HOSTNAME)"
fi

# /etc/hosts entry
if grep -qE "^127\.0\.1\.1\s+$HOSTNAME_FQDN" /etc/hosts; then
    log_skip "/etc/hosts already has $HOSTNAME_FQDN entry"
else
    # remove any old 127.0.1.1 line, then add the correct one
    sed -i '/^127\.0\.1\.1/d' /etc/hosts
    echo "127.0.1.1   $HOSTNAME_FQDN $HOSTNAME_SHORT" >> /etc/hosts
    log_done "/etc/hosts updated with $HOSTNAME_FQDN"
fi

# ============================================================================
# STEP 3: Timezone
# ============================================================================
step "Step 3: Setting timezone to $TIMEZONE"

CURRENT_TZ=$(timedatectl show --property=Timezone --value)
if [ "$CURRENT_TZ" = "$TIMEZONE" ]; then
    log_skip "Timezone already set to $TIMEZONE"
else
    timedatectl set-timezone "$TIMEZONE"
    log_done "Timezone set to $TIMEZONE (was: $CURRENT_TZ)"
fi

# ============================================================================
# STEP 4: Install basic admin tools
# ============================================================================
step "Step 4: Installing basic admin tools"

TOOLS="vim htop curl wget git net-tools dnsutils ufw fail2ban unattended-upgrades"
MISSING=""
for pkg in $TOOLS; do
    if ! dpkg -l "$pkg" 2>/dev/null | grep -q "^ii"; then
        MISSING="$MISSING $pkg"
    fi
done

if [ -z "$MISSING" ]; then
    log_skip "All admin tools already installed"
else
    apt-get install -y -qq -o Dpkg::Use-Pty=0 $MISSING < /dev/null
    log_done "Installed packages:$MISSING"
fi

# ============================================================================
# STEP 5: Create personal admin user
# ============================================================================
step "Step 5: Creating personal admin user '$ADMIN_USER'"

if id "$ADMIN_USER" &>/dev/null; then
    log_skip "User $ADMIN_USER already exists"
else
    useradd -m -s /bin/bash -G sudo "$ADMIN_USER"
    # Use ADMIN_PW from secrets.local if available, otherwise generate
    if [ -z "${ADMIN_PW:-}" ]; then
        ADMIN_PW=$(openssl rand -base64 18 | tr -d '/+=' | head -c 22)
        log_warn "No ADMIN_PW in secrets.local - generated a random password (NOT in CREDENTIALS.txt)"
    fi
    echo "$ADMIN_USER:$ADMIN_PW" | chpasswd
    log_done "Created user $ADMIN_USER (member of sudo group)"
fi

# ============================================================================
# STEP 6: Create shareable admin user
# ============================================================================
step "Step 6: Creating shareable admin user '$SHARED_ADMIN_USER'"

if id "$SHARED_ADMIN_USER" &>/dev/null; then
    log_skip "User $SHARED_ADMIN_USER already exists"
else
    useradd -m -s /bin/bash -G sudo "$SHARED_ADMIN_USER"
    # Use SHARED_ADMIN_PW or fall back to STAFF_PW (older naming) or generate
    if [ -z "${SHARED_ADMIN_PW:-}" ] && [ -n "${STAFF_PW:-}" ]; then
        SHARED_ADMIN_PW="$STAFF_PW"
    fi
    if [ -z "${SHARED_ADMIN_PW:-}" ]; then
        SHARED_ADMIN_PW=$(openssl rand -base64 18 | tr -d '/+=' | head -c 22)
        log_warn "No SHARED_ADMIN_PW in secrets.local - generated a random password (NOT in CREDENTIALS.txt)"
    fi
    echo "$SHARED_ADMIN_USER:$SHARED_ADMIN_PW" | chpasswd
    log_done "Created user $SHARED_ADMIN_USER (member of sudo group)"
fi

# ============================================================================
# STEP 7: SSH hardening - move port, disable root login
# ============================================================================
step "Step 7: SSH hardening"

SSHD_CONFIG="/etc/ssh/sshd_config"
SSHD_BACKUP="/etc/ssh/sshd_config.phase1.bak"

# Backup once
if [ ! -f "$SSHD_BACKUP" ]; then
    cp "$SSHD_CONFIG" "$SSHD_BACKUP"
    log_done "Backed up $SSHD_CONFIG to $SSHD_BACKUP"
fi

# Set port
if grep -qE "^Port $SSH_PORT$" "$SSHD_CONFIG"; then
    log_skip "SSH already configured for port $SSH_PORT"
else
    sed -i '/^Port /d' "$SSHD_CONFIG"
    sed -i '/^#Port /d' "$SSHD_CONFIG"
    echo "Port $SSH_PORT" >> "$SSHD_CONFIG"
    log_done "SSH port set to $SSH_PORT"
fi

# Disable root login
if grep -qE "^PermitRootLogin no$" "$SSHD_CONFIG"; then
    log_skip "Root SSH login already disabled"
else
    sed -i '/^PermitRootLogin /d' "$SSHD_CONFIG"
    sed -i '/^#PermitRootLogin /d' "$SSHD_CONFIG"
    echo "PermitRootLogin no" >> "$SSHD_CONFIG"
    log_done "Root SSH login disabled"
fi

# Ubuntu 24.04+ uses /etc/ssh/sshd_config.d/ snippets - check there too
SSHD_SNIPPET_DIR="/etc/ssh/sshd_config.d"
if [ -d "$SSHD_SNIPPET_DIR" ]; then
    SNIPPET="$SSHD_SNIPPET_DIR/00-phase1.conf"
    cat > "$SNIPPET" <<EOF
Port $SSH_PORT
PermitRootLogin no
EOF
    chmod 644 "$SNIPPET"
    log_done "SSH config snippet written to $SNIPPET"
fi

# Validate config before restarting.
# /run/sshd is required by sshd for privilege separation. It's created
# automatically when sshd is started by systemd, but doesn't necessarily
# exist yet at this point - and `sshd -t` will fail with
# "Missing privilege separation directory: /run/sshd" without it.
mkdir -p /run/sshd
chmod 0755 /run/sshd

if sshd -t 2>/dev/null; then
    log_done "sshd config validated"
else
    # Show the actual error so we know what's wrong
    SSHD_ERR=$(sshd -t 2>&1)
    log_fail "sshd config has errors - NOT restarting SSH. Error: $SSHD_ERR"
fi

# ============================================================================
# STEP 8: Configure firewall (ufw)
# ============================================================================
step "Step 8: Configuring firewall (ufw)"

# Set defaults
ufw default deny incoming >/dev/null 2>&1
ufw default allow outgoing >/dev/null 2>&1

# Allow new SSH port BEFORE enabling firewall, so we don't lock out
if ufw status | grep -qE "^${SSH_PORT}/tcp\s+ALLOW"; then
    log_skip "Firewall already allows port $SSH_PORT/tcp"
else
    ufw allow ${SSH_PORT}/tcp >/dev/null 2>&1
    log_done "Firewall: allow $SSH_PORT/tcp (SSH)"
fi

# Allow standard web ports for later phases
for PORT in 80 443; do
    if ufw status | grep -qE "^${PORT}/tcp\s+ALLOW"; then
        log_skip "Firewall already allows port $PORT/tcp"
    else
        ufw allow ${PORT}/tcp >/dev/null 2>&1
        log_done "Firewall: allow $PORT/tcp"
    fi
done

# Clean up: if port 22 was allowed by a previous run, remove it
if ufw status | grep -qE "^22/tcp\s+ALLOW"; then
    ufw delete allow 22/tcp >/dev/null 2>&1
    log_done "Firewall: removed leftover allow 22/tcp rule (no service listens there)"
fi

# Enable firewall if not active
if ufw status | grep -q "Status: active"; then
    log_skip "Firewall already active"
else
    echo "y" | ufw enable >/dev/null 2>&1
    log_done "Firewall enabled"
fi

# ============================================================================
# STEP 9: Configure fail2ban
# ============================================================================
step "Step 9: Configuring fail2ban"

JAIL_LOCAL="/etc/fail2ban/jail.local"
if [ -f "$JAIL_LOCAL" ] && grep -q "phase1-marker" "$JAIL_LOCAL"; then
    log_skip "fail2ban jail.local already configured"
else
    cat > "$JAIL_LOCAL" <<EOF
# phase1-marker - managed by phase1.sh
[DEFAULT]
bantime  = 1h
findtime = 10m
maxretry = 3

[sshd]
enabled = true
port    = $SSH_PORT
EOF
    log_done "fail2ban configured: 3 attempts, 1-hour ban, watching port $SSH_PORT"
fi

systemctl enable fail2ban >/dev/null 2>&1
systemctl restart fail2ban
if systemctl is-active --quiet fail2ban; then
    log_done "fail2ban running"
else
    log_fail "fail2ban failed to start"
fi

# ============================================================================
# STEP 10: Verify unattended-upgrades
# ============================================================================
step "Step 10: Verifying unattended-upgrades"

if systemctl is-enabled --quiet unattended-upgrades 2>/dev/null; then
    log_skip "unattended-upgrades already enabled"
else
    systemctl enable unattended-upgrades >/dev/null 2>&1
    log_done "unattended-upgrades enabled"
fi

if systemctl is-active --quiet unattended-upgrades; then
    log_done "unattended-upgrades running"
else
    systemctl start unattended-upgrades
    log_done "unattended-upgrades started"
fi

# ============================================================================
# STEP 11: Restart SSH (carefully - handles Ubuntu 24.04+ socket activation)
# ============================================================================
step "Step 11: Restarting SSH"

if sshd -t 2>/dev/null; then
    # Ubuntu 24.04+ uses systemd socket activation: ssh.socket listens for
    # connections and starts ssh.service on demand. When we change the port
    # in sshd_config, the sshd-socket-generator creates a drop-in at
    # /run/systemd/generator/ssh.socket.d/addresses.conf, but systemd does
    # NOT automatically rebind the socket - we have to daemon-reload AND
    # restart ssh.socket. Otherwise the socket remains "active" in systemd's
    # view but isn't actually bound to the new port.
    #
    # Make sure /run/sshd exists (sshd needs it for privilege separation).
    mkdir -p /run/sshd
    chmod 0755 /run/sshd

    systemctl daemon-reload

    # On 24.04+, ssh.socket is the listener. On older releases, ssh.service is.
    # Handle both cases.
    if systemctl list-unit-files ssh.socket 2>/dev/null | grep -q "ssh.socket"; then
        systemctl restart ssh.socket
        # ssh.service may or may not be running (it's started on demand).
        # Restart it if it's active so any existing config is reloaded.
        if systemctl is-active --quiet ssh.service; then
            systemctl restart ssh.service
        fi
        log_done "SSH socket restarted - now listening on port $SSH_PORT (socket activation)"
    else
        systemctl restart ssh
        log_done "SSH service restarted - now listening on port $SSH_PORT"
    fi
else
    log_fail "SSH config invalid, NOT restarted. Check $SSHD_CONFIG and $SSHD_SNIPPET_DIR"
fi

# ============================================================================
# REPORT
# ============================================================================
echo ""
echo "==================================================================="
echo "  PHASE 1 COMPLETE - SUMMARY REPORT"
echo "==================================================================="
echo ""
for line in "${REPORT[@]}"; do
    echo "  $line"
done

echo ""
echo "==================================================================="
echo "  PASSWORDS"
echo "==================================================================="
echo ""
echo "  All passwords are in CREDENTIALS.txt at the repo root."
echo "  This script does NOT print passwords (to avoid scrollback exposure)."
echo ""
echo "  To view the credentials again:"
echo "    cat $(dirname "${BASH_SOURCE[0]}")/../CREDENTIALS.txt"
echo ""

echo "==================================================================="
echo "  AUTOMATED VERIFICATION"
echo "==================================================================="
echo ""

VERIFY_PASS=0
VERIFY_FAIL=0

verify() {
    local description="$1"
    local expected="$2"
    local actual="$3"
    if [ "$expected" = "$actual" ]; then
        echo "  [PASS] $description"
        VERIFY_PASS=$((VERIFY_PASS + 1))
    else
        echo "  [FAIL] $description"
        echo "         expected: $expected"
        echo "         actual:   $actual"
        VERIFY_FAIL=$((VERIFY_FAIL + 1))
    fi
}

verify_contains() {
    local description="$1"
    local haystack="$2"
    local needle="$3"
    if echo "$haystack" | grep -q "$needle"; then
        echo "  [PASS] $description"
        VERIFY_PASS=$((VERIFY_PASS + 1))
    else
        echo "  [FAIL] $description"
        echo "         looking for: $needle"
        echo "         in:          $haystack"
        VERIFY_FAIL=$((VERIFY_FAIL + 1))
    fi
}

verify_not_contains() {
    local description="$1"
    local haystack="$2"
    local needle="$3"
    if echo "$haystack" | grep -q "$needle"; then
        echo "  [FAIL] $description"
        echo "         unexpectedly found: $needle"
        VERIFY_FAIL=$((VERIFY_FAIL + 1))
    else
        echo "  [PASS] $description"
        VERIFY_PASS=$((VERIFY_PASS + 1))
    fi
}

# Hostname
verify "Hostname is $HOSTNAME_SHORT" "$HOSTNAME_SHORT" "$(hostname)"

# /etc/hosts
verify_contains "/etc/hosts has FQDN entry" "$(cat /etc/hosts)" "$HOSTNAME_FQDN"

# Timezone
verify "Timezone is $TIMEZONE" "$TIMEZONE" "$(timedatectl show --property=Timezone --value)"

# Personal admin user
if id "$ADMIN_USER" &>/dev/null; then
    echo "  [PASS] Personal admin user '$ADMIN_USER' exists"
    VERIFY_PASS=$((VERIFY_PASS + 1))
    verify_contains "Personal admin user '$ADMIN_USER' is in sudo group" \
        "$(id "$ADMIN_USER")" "sudo"
else
    echo "  [FAIL] Personal admin user '$ADMIN_USER' does not exist"
    VERIFY_FAIL=$((VERIFY_FAIL + 1))
fi

# Shareable admin user
if id "$SHARED_ADMIN_USER" &>/dev/null; then
    echo "  [PASS] Shareable admin user '$SHARED_ADMIN_USER' exists"
    VERIFY_PASS=$((VERIFY_PASS + 1))
    verify_contains "Shareable admin user '$SHARED_ADMIN_USER' is in sudo group" \
        "$(id "$SHARED_ADMIN_USER")" "sudo"
else
    echo "  [FAIL] Shareable admin user '$SHARED_ADMIN_USER' does not exist"
    VERIFY_FAIL=$((VERIFY_FAIL + 1))
fi

# SSH listening
LISTENING=$(ss -tlnp 2>/dev/null)
verify_contains "SSH listening on port $SSH_PORT" "$LISTENING" ":$SSH_PORT "
verify_not_contains "SSH NOT listening on port 22" "$LISTENING" ":22 "

# SSH config
SSHD_EFFECTIVE=$(sshd -T 2>/dev/null)
verify_contains "sshd effective config: Port $SSH_PORT" "$SSHD_EFFECTIVE" "^port $SSH_PORT$"
verify_contains "sshd effective config: PermitRootLogin no" "$SSHD_EFFECTIVE" "^permitrootlogin no$"

# Firewall
UFW_STATUS=$(ufw status 2>/dev/null)
verify_contains "Firewall is active" "$UFW_STATUS" "Status: active"
verify_contains "Firewall allows port $SSH_PORT/tcp" "$UFW_STATUS" "$SSH_PORT/tcp"
verify_contains "Firewall allows 80/tcp" "$UFW_STATUS" "80/tcp"
verify_contains "Firewall allows 443/tcp" "$UFW_STATUS" "443/tcp"
verify_not_contains "Firewall does NOT allow port 22/tcp" "$UFW_STATUS" "^22/tcp"

# Services
if systemctl is-active --quiet fail2ban; then
    echo "  [PASS] fail2ban service is active"
    VERIFY_PASS=$((VERIFY_PASS + 1))
else
    echo "  [FAIL] fail2ban service is not active"
    VERIFY_FAIL=$((VERIFY_FAIL + 1))
fi

if fail2ban-client status sshd &>/dev/null; then
    echo "  [PASS] fail2ban sshd jail is active"
    VERIFY_PASS=$((VERIFY_PASS + 1))
else
    echo "  [FAIL] fail2ban sshd jail is not active"
    VERIFY_FAIL=$((VERIFY_FAIL + 1))
fi

# SSH listener is active. On Ubuntu 24.04+ this is ssh.socket; on older
# releases it's ssh.service. Check whichever applies.
if systemctl list-unit-files ssh.socket 2>/dev/null | grep -q "ssh.socket"; then
    if systemctl is-active --quiet ssh.socket; then
        echo "  [PASS] ssh.socket is active (port $SSH_PORT bound via socket activation)"
        VERIFY_PASS=$((VERIFY_PASS + 1))
    else
        echo "  [FAIL] ssh.socket is not active"
        VERIFY_FAIL=$((VERIFY_FAIL + 1))
    fi
else
    if systemctl is-active --quiet ssh; then
        echo "  [PASS] ssh service is active"
        VERIFY_PASS=$((VERIFY_PASS + 1))
    else
        echo "  [FAIL] ssh service is not active"
        VERIFY_FAIL=$((VERIFY_FAIL + 1))
    fi
fi

# Verify the port is actually bound (not just that the unit thinks it is).
# This catches the case where ssh.socket reports active but isn't bound to
# the new port because daemon-reload wasn't called.
if ss -tlnp 2>/dev/null | grep -qE ":${SSH_PORT}\s"; then
    echo "  [PASS] Port $SSH_PORT is actually bound and listening"
    VERIFY_PASS=$((VERIFY_PASS + 1))
else
    echo "  [FAIL] Port $SSH_PORT not actually bound (try: systemctl daemon-reload && systemctl restart ssh.socket)"
    VERIFY_FAIL=$((VERIFY_FAIL + 1))
fi

if systemctl is-enabled --quiet unattended-upgrades 2>/dev/null; then
    echo "  [PASS] unattended-upgrades is enabled"
    VERIFY_PASS=$((VERIFY_PASS + 1))
else
    echo "  [FAIL] unattended-upgrades is not enabled"
    VERIFY_FAIL=$((VERIFY_FAIL + 1))
fi

# Local SSH port responds
if timeout 2 bash -c "</dev/tcp/127.0.0.1/$SSH_PORT" 2>/dev/null; then
    echo "  [PASS] SSH port $SSH_PORT responds locally"
    VERIFY_PASS=$((VERIFY_PASS + 1))
else
    echo "  [FAIL] SSH port $SSH_PORT does not respond locally"
    VERIFY_FAIL=$((VERIFY_FAIL + 1))
fi

# Port 22 NOT responding
if timeout 2 bash -c "</dev/tcp/127.0.0.1/22" 2>/dev/null; then
    echo "  [FAIL] Port 22 still responds (should be closed)"
    VERIFY_FAIL=$((VERIFY_FAIL + 1))
else
    echo "  [PASS] Port 22 not responding (correctly closed)"
    VERIFY_PASS=$((VERIFY_PASS + 1))
fi

echo ""
echo "  Verification: $VERIFY_PASS passed, $VERIFY_FAIL failed"
echo ""

if [ "$VERIFY_FAIL" -gt 0 ]; then
    echo "  *** $VERIFY_FAIL CHECK(S) FAILED. Review failures above before proceeding. ***"
    echo ""
fi

# ============================================================================
# Remove the "NOT YET ACTIVE" warning from CREDENTIALS.txt now that phase 1
# has actually created the users and switched SSH. Only do this if all checks
# passed - if anything failed, leave the warning in place because the
# credentials probably still won't work.
# ============================================================================
CREDENTIALS_FILE="$(dirname "$0")/../CREDENTIALS.txt"
if [ "$VERIFY_FAIL" -eq 0 ] && [ -f "$CREDENTIALS_FILE" ]; then
    if grep -q "NOT YET ACTIVE" "$CREDENTIALS_FILE"; then
        # Strip the 6-line warning block (header + 4 body lines + separator).
        # Sed deletes from the "*** NOT YET ACTIVE" line through the
        # "------" separator that closes the warning.
        sed -i '/\*\*\* NOT YET ACTIVE/,/^  ---/d' "$CREDENTIALS_FILE"
        log_done "Removed 'NOT YET ACTIVE' warning from CREDENTIALS.txt (SSH login is now live)"
    fi
fi

echo "==================================================================="
echo "  MANUAL VERIFICATION STEPS (cannot be automated)"
echo "==================================================================="
cat <<EOF

  These steps require an external connection and CANNOT be checked
  by this script. Do them from your Windows machine while keeping
  this session open as a safety net.

  IMPORTANT: get the password for $ADMIN_USER from CREDENTIALS.txt
  BEFORE you try to SSH. Three wrong attempts = 1-hour fail2ban
  lockout from your IP.

  1. Open a NEW terminal window and SSH in as your personal admin:
       ssh -p $SSH_PORT $ADMIN_USER@$SERVER_IP
     This proves the new port and user account work end-to-end.

  2. Verify root SSH is rejected (do this from another new session):
       ssh -p $SSH_PORT root@$SERVER_IP
     This should fail with "Permission denied".

  3. Confirm CREDENTIALS.txt is saved in your password manager.

  4. (Optional) Clear your terminal scrollback:
       clear && history -c

  Once these checks are done, Phase 1 is fully complete and you
  can proceed to Phase 2 (Web server + TLS foundation).

EOF
echo "==================================================================="

# Exit with non-zero status if any automated check failed
if [ "$VERIFY_FAIL" -gt 0 ]; then
    exit 1
fi
exit 0
