#!/bin/bash
#
# phase-post-hetzner-dkim.sh - Read the DKIM key generated by phase 4 and
#                              publish it as a TXT record in Hetzner DNS.
#
# Runs AFTER phase4.sh on the server. Closes the last remaining manual DNS
# step in the build.
#
# Idempotent. Safe to re-run: PUTs the RRSet, replacing any prior value.
#
# Run on the server as root:
#   sudo bash scripts/phase-post-hetzner-dkim.sh
#

set -u

# ============================================================================
# PATHS
# ============================================================================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
LIB_DIR="$SCRIPT_DIR/lib"
TENANT_FILE="$REPO_ROOT/tenant.local"
HETZNER_FILE="$REPO_ROOT/hetzner.local"

# Load helpers
# shellcheck source=lib/hetzner-api.sh
source "$LIB_DIR/hetzner-api.sh"
# hetzner-api.sh reads HCLOUD_LAST_STATUS; pre-set it so nounset (set -u)
# does not abort before the first API call records a status. This matches
# how phase-pre-hetzner.sh initializes it after sourcing the library.
HCLOUD_LAST_STATUS=""

# Load shared helpers and per-tenant config (colors, logging, verify helpers).
# SCRIPT_DIR/REPO_ROOT are defined above; lib/common.sh also sources
# tenant.local/secrets.local if they exist.
# shellcheck disable=SC1091
source "$SCRIPT_DIR/lib/common.sh"


# ============================================================================
# PRE-FLIGHT
# ============================================================================
echo ""
echo "${BOLD}===================================================================${RESET}"
echo "${BOLD}  PHASE POST-HETZNER-DKIM - Publish DKIM TXT record${RESET}"
echo "${BOLD}===================================================================${RESET}"

step "Pre-flight"

# Required: jq for JSON, openssl is not needed here but the lib expects it
if ! command -v jq >/dev/null 2>&1; then
    log_fail "jq is required. Install with: sudo apt-get install -y jq"
    exit 1
fi
log_done "jq present"

# Source tenant.local to get DOMAIN
if [ ! -f "$TENANT_FILE" ]; then
    log_fail "$TENANT_FILE not found. Did phase0-bootstrap.sh run?"
    exit 1
fi
# shellcheck disable=SC1090
source "$TENANT_FILE"
if [ -z "${DOMAIN:-}" ]; then
    log_fail "DOMAIN not set in $TENANT_FILE"
    exit 1
fi
log_done "DOMAIN: $DOMAIN"

# Source hetzner.local for the token + zone ID
if [ ! -f "$HETZNER_FILE" ]; then
    log_fail "$HETZNER_FILE not found. Did phase-pre-hetzner.sh run?"
    echo ""
    echo "  If you provisioned the server some other way and just want to push"
    echo "  the DKIM record, you can create $HETZNER_FILE manually with:"
    echo "    HETZNER_CLOUD_TOKEN=\"...\""
    echo "    HETZNER_ZONE_ID=\"...\""
    exit 1
fi
# shellcheck disable=SC1090
source "$HETZNER_FILE"
if [ -z "${HETZNER_CLOUD_TOKEN:-}" ] || [ -z "${HETZNER_ZONE_ID:-}" ]; then
    log_fail "HETZNER_CLOUD_TOKEN or HETZNER_ZONE_ID missing in $HETZNER_FILE"
    exit 1
fi
export HETZNER_CLOUD_TOKEN
log_done "Hetzner token + zone id loaded"

# ============================================================================
# DKIM KEY EXTRACTION
# ============================================================================
step "Extract DKIM record from /etc/opendkim/keys/${DOMAIN}/default.txt"

DKIM_SELECTOR="${DKIM_SELECTOR:-default}"
DKIM_KEY_FILE="/etc/opendkim/keys/${DOMAIN}/${DKIM_SELECTOR}.txt"

if [ ! -f "$DKIM_KEY_FILE" ]; then
    log_fail "DKIM key file not found: $DKIM_KEY_FILE"
    echo "  This script must run AFTER phase4.sh, on the server itself."
    exit 1
fi

# Same parser as phase4.sh uses for the BIND zone file: pull everything
# between the first ( and the last ), preserving the quoted-string structure.
# This handles both "single quoted string" and "split quoted strings" formats.
DKIM_VALUE=$(awk '
    /^[a-zA-Z0-9_]+\._domainkey/ { in_record = 1 }
    in_record {
        line = $0
        sub(/.*\(/, "", line)
        sub(/\).*/, "", line)
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", line)
        if (length(line) > 0) {
            if (out) { out = out " " line } else { out = line }
        }
        if (/\)/) { in_record = 0 }
    }
    END { print out }
' "$DKIM_KEY_FILE")

if [ -z "$DKIM_VALUE" ]; then
    log_fail "Could not parse DKIM record from $DKIM_KEY_FILE"
    exit 1
fi

# Hetzner's TXT record value field accepts the full quoted-string structure
# that BIND emits (e.g. "v=DKIM1; h=sha256; ..." "p=MIIBIjAN..."). The DNS
# server reassembles split strings transparently when answering queries.
# We pass the parsed value through verbatim.
log_done "Parsed DKIM key ($(echo -n "$DKIM_VALUE" | wc -c) chars)"

# ============================================================================
# VALIDATE TOKEN
# ============================================================================
step "Validate Hetzner API token"

if hcloud_validate_token; then
    log_done "Token is valid"
else
    log_fail "Token rejected"
    exit 1
fi

# ============================================================================
# UPSERT DKIM RRSet
# ============================================================================
step "Publish DKIM record"

# Record name is "default._domainkey" relative to the zone apex.
DKIM_NAME="${DKIM_SELECTOR}._domainkey"

# Build the RRSet body. The DKIM value already contains the quote
# characters from the BIND format, so it's passed as-is.
DKIM_BODY=$(jq -n \
    --arg name "$DKIM_NAME" \
    --argjson ttl 3600 \
    --arg value "$DKIM_VALUE" \
    '{name: $name, type: "TXT", ttl: $ttl, records: [{value: $value}]}')

# Check if RRSet exists; PUT to update, POST to create.
hcloud_get "/zones/${HETZNER_ZONE_ID}/rrsets/${DKIM_NAME}/TXT" >/dev/null
if [ "$HCLOUD_LAST_STATUS" = "200" ]; then
    echo "  Existing DKIM RRSet found - updating in place"
    # The rrset PUT endpoint cannot change records, only metadata. Delete the
    # existing RRSet and recreate it via the create endpoint, which is the
    # only one that accepts a records payload. Keeps the phase idempotent.
    hcloud_delete "/zones/${HETZNER_ZONE_ID}/rrsets/${DKIM_NAME}/TXT" >/dev/null 2>&1 || true
    RESP=$(hcloud_post "/zones/${HETZNER_ZONE_ID}/rrsets" "$DKIM_BODY")
    EXPECTED_STATUS=200
else
    echo "  No existing DKIM RRSet - creating"
    RESP=$(hcloud_post "/zones/${HETZNER_ZONE_ID}/rrsets" "$DKIM_BODY")
    EXPECTED_STATUS=201
fi

# HCLOUD_LAST_STATUS is unreliable here: hcloud_post/hcloud_put run inside
# $(...) command substitution, so the status never reaches this shell.
# Decide success from the response body - a created or updated RRSet
# always comes back with .rrset.id populated.
if echo "$RESP" | jq -e '.rrset.id' >/dev/null 2>&1; then
    log_done "DKIM TXT record published at ${DKIM_NAME}.${DOMAIN}"
else
    log_fail "Publish failed"
    echo "$RESP" | jq -r '.error.message // .' >&2
    exit 1
fi

# ============================================================================
# VERIFICATION
# ============================================================================
step "Verification"

cat <<EOF

  DKIM record published. To verify externally (give DNS a few minutes
  to propagate first):

    dig +short TXT ${DKIM_NAME}.${DOMAIN}

  Or with a public resolver:

    dig +short TXT ${DKIM_NAME}.${DOMAIN} @1.1.1.1

  You should see the v=DKIM1 record. If it shows the wrong value or no
  value, check Hetzner Console -> DNS -> ${DOMAIN}.

  Send a test mail to https://www.mail-tester.com to confirm DKIM
  signing works end-to-end (Postfix + OpenDKIM + DNS).

EOF
